#!/usr/bin/env bash
set -eo pipefail

if [[ ! -x "$(command -v doctl)" ]]; then
  echo "doctl command not found, please install it."
  exit 1
fi

main() {
  doctl compute droplet list --tag-name promoted --no-header --format ID
}

main
