#!/usr/bin/env bash
set -eo pipefail

if [[ ! -x "$(command -v doctl)" ]]; then
  echo "doctl command not found, please install it."
  exit 1
fi

main() {
  local id="$1"

  [[ -z "$id" ]] && echo "Error: missing argument droplet ID" && exit 1

  local old=$(doctl compute droplet list --tag-name promoted --no-header --format ID)

  echo "==> Unpromoting $old"
  doctl compute droplet untag "$old" --tag-name promoted

  echo "==> Promoting $id"
  doctl compute droplet tag "$id" --tag-name promoted
}

echo "=> Promoting server"
main "$1"
