#!/usr/bin/env bash
set -eo pipefail

if [[ ! -x "$(command -v doctl)" ]]; then
  echo "doctl command not found, please install it."
  exit 1
fi

main() {
  local id="$1"
  local ip="45.55.125.113"

  [[ -z "$id" ]] && echo "Error: missing argument droplet ID" && exit 1

  echo "==> Switching floating IP $ip to $id"
  doctl compute floating-ip-action assign "$ip" "$id"
}

main "$1"
