#!/usr/bin/env bash
set -eo pipefail

source /dev/stdin <<< "$(curl -Lsm 2 https://get.belt.sh)"

main() {
  local host="$1"
  local password="$2"

  [[ -z "$host" ]] && echo "Error: missing argument host" && exit 1

  belt_begin_session "root" "$host"

  echo -n "==> Installing postgres"
  postgres_install
  echo "  OK"

  echo -n "==> Uploading pg_hba.conf"
  belt_remote_upload "files/postgres/pg_hba.conf"
  echo "  OK"

  echo -n "==> Restarting postgres"
  systemd_unit_restart "postgresql@11-main"
  echo "  OK"
}

echo "=> Provisioning postgres"
main "$1" "$2"
