#!/usr/bin/env bash
set -eo pipefail

BELT_ENV_TOOLBOX_TOOLS="postgresql"

source /dev/stdin <<< "$(curl -Lsm 2 https://get.belt.sh)"

main() {
  local host="$1"
  local password="$2"

  [[ -z "$host" ]] && echo "Error: missing argument host" && exit 1

  belt_begin_session "root" "$host"

  echo -n "==> Installing postgresql "
  postgresql_install
  echo "OK"

  echo -n "==> Restarting postgresql "
  postgresql_restart
  echo "OK"
}

echo "=> Provisioning postgres"
main "$1" "$2"
