#!/usr/bin/env bash
set -eo pipefail

source /dev/stdin <<< "$(curl -Lsm 2 https://get.belt.sh)"

main() {
  local host="$1"
  local password="$2"

  [[ -z "$host" ]] && echo "Error: missing argument host" && exit 1
  [[ -z "$password" ]] && echo "Error: missing argument password" && exit 1

  belt_begin_session "root" "$host"

  echo -n "==> Creating database"
  postgres_create_database "memoir"
  echo "  OK"

  echo -n "==> Creating role"
  postgres_create_role "memoir" "$password"
  echo "  OK"

  echo -n "==> Granting privileges"
  postgres_add_role_to_db "memoir" "memoir"
  echo "  OK"
}

echo "=> Provisioning database"
main "$1" "$2"
