#!/usr/bin/env bash
set -eo pipefail

BELT_ENV_TOOLBOX_TOOLS="postgresql"

source /dev/stdin <<< "$(curl -Lsm 2 https://get.belt.sh)"

main() {
  local host="$1"
  local password="$2"

  [[ -z "$host" ]] && echo "Error: missing argument host" && exit 1
  [[ -z "$password" ]] && echo "Error: missing argument password" && exit 1

  belt_begin_session "root" "$host"

  echo -n "==> Creating database "
  postgresql_create_database "memoir"
  echo "OK"

  echo -n "==> Creating role "
  postgresql_create_role "memoir" "$password"
  echo "OK"

  echo -n "==> Granting privileges "
  postgresql_add_role_to_database "memoir" "memoir"
  echo "OK"
}

echo "=> Provisioning database"
main "$1" "$2"
