#!/usr/bin/env bash
set -eo pipefail

source /dev/stdin <<< "$(curl -Lsm 2 https://get.belt.sh)"

main() {
  local host="$1"

  [[ -z "$host" ]] && echo "Error: missing argument host" && exit 1

  belt_begin_session "root" "$host"

  echo -n "==> Installing caddy"
  caddy_install
  echo "  OK"

  echo -n "==> Starting caddy"
  caddy_start
  echo "  OK"
}

echo "=> Provisioning HTTP server"
main "$1"
