#!/usr/bin/env bash
set -eo pipefail

if [[ ! -x "$(command -v doctl)" ]]; then
  echo "doctl command not found, please install it."
  exit 1
fi

main() {
  local name="$1"
  local fingerprint="$2"

  [[ -z "$name" ]] && echo "Error: missing argument name" && exit 1
  [[ -z "$name" ]] && echo "Error: missing argument SSH key fingerprint" && exit 1

  # TODO: extract configuration into environment variable based config file?

  echo -n "==> Creating droplet "
  doctl compute droplet create "$name" \
    --region nyc3 \
    --image ubuntu-18-04-x64 \
    --size s-1vcpu-1gb \
    --ssh-keys "$fingerprint" \
    --no-header \
    --format ID \
    --wait
}

echo "=> Provisioning server"
main "$1" "$2"
