#!/usr/bin/env bash
set -eo pipefail

BELT_ENV_TOOLBOX_TOOLS="caddy"

source /dev/stdin <<< "$(curl -Lsm 2 https://get.belt.sh)"

ARCHIVE_FILE="/tmp/memoir-app.tar.gz"

main() {
  local host="$1"

  [[ -z "$host" ]] && echo "Error: missing argument host" && exit 1
  [[ ! -e "$ARCHIVE_FILE" ]] && echo "Error: missing archive $ARCHIVE_FILE" && exit 1

  belt_begin_session "root" "$host"

  echo -n "==> Uploading app archive "
  app_upload "$ARCHIVE_FILE"
  echo "OK"

  echo -n "==> Copying files "
  app_copy_directory "public"
  echo "OK"

  echo -n "==> Setting up permissions "
  app_set_permissions "www-data:www-data"
  echo "OK"

  echo -n "==> Adding caddy vhost "
  caddy_add_vhost
  echo "OK"

  echo -n "==> Restarting caddy "
  caddy_restart
  echo "OK"
}

echo "=> Deploying memoir-app"
main "$1"
