#!/usr/bin/env bash
set -eo pipefail

source /dev/stdin <<< "$(curl -Lsm 2 https://get.belt.sh)"

ARCHIVE_FILE="/tmp/memoir-app.tar.gz"

main() {
  local host="$1"

  [[ -z "$host" ]] && echo "Error: missing argument host" && exit 1
  [[ ! -e "$ARCHIVE_FILE" ]] && echo "Error: missing archive $ARCHIVE_FILE" && exit 1

  belt_begin_session "root" "$host"

  echo "Uploading app archive..."
  app_upload "$ARCHIVE_FILE"

  echo "Copying files..."
  app_copy_directory "public"

  echo "Setting up permissions..."
  app_set_permissions "www-data:www-data"

  echo "Adding caddy vhost..."
  app_add_caddy_vhost

  echo "Restarting caddy..."
  caddy_restart
}

main "$1"
